### ISSUE TITLE
Strange method name

### ISSUE THREAD

**Issue by RoXuS** [acacode/swagger-typescript-api#152]
Several of our methods has a number after there name:

```
  searchConsumption1 = (data: { filters?: CreditOperationFilters; pageable?: Pageable }, params?: RequestParams) =>
```

Ok we have this method in another class but not in the same class. We generate API with `modular`.

**Comment by js2me** [comment]
Hello @RoXuS  
Can you share part of schema where contains original `searchConsumption` and "duplicate" `searchConsumption` ?   
And which version of swagger schema are you using ?   
Just currently I'm not see a problem with local version.

**Comment by js2me** [comment]
@RoXuS did you see this message on console output ? `Module "{moduleName}" already have method "{methodName}()"` ?

**Comment by RoXuS** [comment]
No we don't have this log.
Our schema:
```"/organizations/{organizationId}/credits/search-consumption": {
      "post": {
        "tags": [
          "credit-operation-api"
        ],
        "operationId": "searchConsumption",
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "filters": {
                    "$ref": "#/components/schemas/CreditOperationFilters"
                  },
                  "pageable": {
                    "$ref": "#/components/schemas/Pageable"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/CreditPageCreditConsumptionDto"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },

**Comment by js2me** [comment]
@RoXuS I hope that this problem was fixed in 5.0.0 :)   
If not please reopen issue or ping me here

**Comment by RoXuS** [comment]
hey,

with 5.0.0, the error remains, for example
```
  /**
   * No description
   *
   * @tags credit-operation-api
   * @name SearchConsumption1
   * @request POST:/me/organization/credits/search-consumption
   * @secure
   */
  searchConsumption1 = (
    data: CreditOperationFilters,
    query?: { page?: number; size?: number; sort?: string[] },
    params: RequestParams = {},
  ) => ...
  ```

  
  But we have less duplicate than on 4.4.0!
  
  For info our two different schema:
  
  ```
  "/organizations/{organizationId}/credits/search-consumption": {
      "post": {
        "tags": [
          "credit-operation-api"
        ],
        "operationId": "searchConsumption",
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "Zero-based page index (0..N)",
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "size",
            "in": "query",
            "description": "The size of the page to be returned",
            "schema": {
              "type": "integer",
              "default": 20
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreditOperationFilters"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/CreditPageCreditConsumptionDto"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    }
    ```
    ```
    "/me/organization/credits/search-consumption": {
      "post": {
        "tags": [
          "credit-operation-api"
        ],
        "operationId": "searchConsumption_1",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Zero-based page index (0..N)",
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "size",
            "in": "query",
            "description": "The size of the page to be returned",
            "schema": {
              "type": "integer",
              "default": 20
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreditOperationFilters"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/hal+json": {
                "schema": {
                  "$ref": "#/components/schemas/CreditPageCreditConsumptionDto"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    ```
    
    Thx for your 5.0.0!

**Comment by RoXuS** [comment]
other info 
![Uploading image.png…]()

**Comment by js2me** [comment]
Hi @RoXuS !   
Can you message all operations ids of this  `execureSearch` operations ?

**Comment by js2me** [comment]
Just I think ending number it is a part of `"operationId"` field   
like `searchConsumption_1`

**Comment by RoXuS** [comment]
Yeah we have
```
"/me/organization/credits/search-consumption": {
      "post": {
        "tags": [
          "credit-operation-api"
        ],
        "operationId": "searchConsumption_1",
        "parameters": [
          {
          ...
          ```
For example.

**Comment by RoXuS** [comment]
So the issue is on our swagger generator ?

**Comment by js2me** [comment]
@RoXuS If you don't see this message  
![image](https://user-images.githubusercontent.com/16340911/107925265-40987980-6f85-11eb-8a14-897f3f9898b3.png)
It means that the number endings goes from "operationId" field  

I'll try to fix that at next release.   
Definetely swagger-typescript-api codegenerator should crop `_1`, `_2`, `_{n}` in "operationId"   

Currently, as quick solution you can customize route name with hook `onCreateRouteName()` (version 5.1.0)

**Comment by RoXuS** [comment]
We will wait your new version, np.

Thx!!

**Comment by amankkg** [comment]
Here is my temporary solution as @js2me suggested
```js
onCreateRouteName: (nameInfo, rawInfo) => {
  nameInfo.original = nameInfo.original.replace(/\d+$/, '')
  nameInfo.usage = nameInfo.usage.replace(/\d+$/, '')
},
```

**Comment by Grawl** [comment]
Just faced this issue with following config:

```ts
import { generateApi } from 'swagger-typescript-api';
import { resolve } from 'node:path';

void generateApi({
  url: 'https://my-domain.tld/api/v3/api-docs',
  output: resolve(process.cwd(), 'src/shared/api'),
  name: 'generated',
  generateClient: true,
  httpClientType: 'axios',
});
```

solution from @amankkg is working for me
