### ISSUE TITLE
Type collisions in Axios HTTP client

### ISSUE THREAD

**Issue by szymon-99** [acacode/swagger-typescript-api#331]
Right now when setting 

`httpClientType: "axios"`

Inside HTTPClient class there are some type collisions when constructing headers

![mergeRequestParams](https://user-images.githubusercontent.com/81956806/149121542-3b430d40-e516-4bf1-82a6-2c508933c9f2.png)

![request](https://user-images.githubusercontent.com/81956806/149121575-e1109bcb-9a36-4bd7-82bb-148920aa0121.png)

I assume this file is autogenerated from [here](https://github.com/acacode/swagger-typescript-api/blob/master/templates/base/http-clients/axios-http-client.eta)

**Comment by cardinalX** [comment]
You can use axios with version 0.21.4
```
"dependencies": {
    "axios": "^0.21.4",
```

**Comment by SLG** [comment]
> You can use axios with version 0.21.4
> 
> ```
> "dependencies": {
>     "axios": "^0.21.4",
> ```

While this works, of course, it's not a real solution.
Is there any progress made on this?

**Comment by Liwoj** [comment]
The problem was introduced with [this commit](https://github.com/axios/axios/commit/94a93447992392441f1928dffc9f10529ecec417) in Axios 0.23.0 by adding explicit type for default headers.

This should not be too hard to fix. I can do the PR, just need some feedback on my initial analysis (due to my limited experience and usage of/with the generator):

1. `mergeRequestParams` - I don't understand why this function works with Axios defaults (`this.instance.defaults` and `this.instance.defaults.headers`) in the first place. Defaults are set on the instance and will be merged into a request config by Axios itself. So these lines can be safely removed
2. `request` function (`if (type === ContentType.FormData` condition) - little bit harder to make a call as I don't understand the reason for the code and even the [PR which introduced it](https://github.com/acacode/swagger-typescript-api/pull/244)  is not clear why it manipulates the headers (almost feels like it was just useful for the contributor himself for his use case). **Anyway** `common`, `put` etc. keys are not allowed on `headers` key of the request config and must be removed

Any feedback appreciated

**Comment by furkanarabaci** [comment]
Fingers crossed for compatible fix with axios 0.24 🤞

**Comment by stavalfi** [comment]
any update?

**Comment by snufkind** [comment]
Is this fixed yet? Would love to update axios to latest version.

**Comment by inomn** [comment]
any updates on that? thanks.

**Comment by ApacheEx** [comment]
as workaround, you can remove default headers from the api instance.

```
const api = new Api();

api.instance.defaults.headers.put = {};
api.instance.defaults.headers.post = {};
api.instance.defaults.headers.patch = {};


api.auth.login()
```


now, `type: ContentType.Json` is working properly. I will try to create a PR to fix this behavior (so, `type` prop will have more prio)

**Comment by ApacheEx** [comment]
Actually, it's already fixed in https://github.com/acacode/swagger-typescript-api/commit/94087eca8ff3d717fec054725c159e8f9f5d9cb8

**Comment by bezvrednyy** [comment]
I also have a type problem (axios 0.21.4)
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/61377069/187828296-10e9cb29-7317-42b6-894f-2ecf4cda1616.png">

this is used here
<img width="959" alt="image" src="https://user-images.githubusercontent.com/61377069/187828359-eaa2c56e-9b37-4a56-be36-b17d081a2c6a.png">

But if you just delete `HeadersDefaults` everything is fine.

**Comment by otom8-io** [comment]
This issue still occurs for me: 
```
ERROR in ./src/js/api/swagger/http-client.ts:12:67
TS2614: Module '"axios"' has no exported member 'HeadersDefaults'. Did you mean to use 'import HeadersDefaults from "axios"' instead?
    10 |  */
    11 |
  > 12 | import axios, { AxiosInstance, AxiosRequestConfig, AxiosResponse, HeadersDefaults, ResponseType } from "axios";
```

Package.json has:
- "axios": "^0.21.4"
- swagger-typescript-api": "^12.0.4"
